source 'https://rubygems.org'

gem 'dashing'
gem 'aws-sdk', '~> 2.2'
gem 'json', '~> 1.8'
gem 'pry', '~> 0.10'
gem 'rest-client', '~> 1.8'
gem 'rubocop', '~> 0.35'
gem 'google-api-client', '~> 0.8'
gem 'octokit', '~> 4.2'
gem 'nokogiri', '~> 1.6.6'
